
server:
  port: 8080
  
 
spring:
  application:
    name: mbp-api-gateway
#  cloud:
#    gateway:
#    discovery:
#      locator:
#        enabled: true
#      routes:
#      - id: movie-catalog
#        uri: localhost:9091/idx/
#        predicates:
#        - Path=/idx/**            

eureka:
   instance:
      hostname: localhost
   client:
    service-url:
      defaultZone: http://localhost:8761/eureka      